### ISSUE TITLE
Application can't get VP9, VP8 only

### ISSUE THREAD

**Issue by abriginets** [Kagami/wybm#1]
I used the program for a week and everything was fine, but then programm stoped parsing VP9. VP8 only. I used to be able to download, for example, _PSY - Daddy_ in VP9 and now the program offers me only VP8. What's wrong?

**Comment by Kagami** [comment]
Could you please share video url?

**Comment by abriginets** [comment]
Yep. Here it is: https://www.youtube.com/watch?v=FrG4TEcSuRg

**Comment by Kagami** [comment]
This is due to youtube site update, now it returns only VP8 with bundled version of youtube-dl. Thanks for the report, I will release new version soon.

**Comment by abriginets** [comment]
Thanks a lot. Can't wait for update :3

**Comment by Kagami** [comment]
Done. Please try `0.3.0`.
