### ISSUE TITLE
(feature request) subtitles?

### ISSUE THREAD

**Issue by Ungaminga** [Kagami/wybm#16]
Can i choose subtitles from youtube?

**Comment by Kagami** [comment]
Not implemented. Technically possible but webms are mostly useful in web and browsers don't support embedded softsubs.

[boram](https://github.com/Kagami/boram) can download subtitles and hardsub them into resulting video.

**Comment by Ungaminga** [comment]
So i should using [boram](https://github.com/Kagami/boram) for hardsubing?

**Comment by Kagami** [comment]
Yes. wybm doesn't re-encode video.
