### ISSUE TITLE
[Реквест Фичи] Кнопка "Назад"

### ISSUE THREAD

**Issue by abriginets** [Kagami/wybm#4]
Предлагаю сделать кнопку назад в меню выбора формата WEBM. В случае, если Ютуб ещё не заенкодил видео в .webm, появляется пустое поле с видео-форматом и поле с надписью "none" в поле звука. И чтобы загрузить другой файл, нужно закрывать и открывать программу. А я предлагаю влепить кнопку возврата на страницу вставки ссылки.

**Comment by Kagami** [comment]
Так есть же Cancel, не?
![wybm-cancel](https://cloud.githubusercontent.com/assets/533383/17717161/70215a46-641d-11e6-83ba-c24287ab4f5b.png)

**Comment by abriginets** [comment]
И правда, в глаза долблюсь.
